### ISSUE TITLE
How do I get the vminfo quicker.

### ISSUE THREAD

**Issue by Daruptek** [vmware-archive/pyvmomi-tools#1]
We have around 1500 VM's perc vCenter and around 10vCenter's globally.

To get the particular VM info, I am doing this and it is taking really a long time.

container = content.viewManager.CreateContainerView(content.rootFolder, [vim.VirtualMachine], True)
for c in container.view:
if c.name == name:
yourvm = c
break
return yourvm

.......
Retrieving the info from the object like before
print yourvm.runtime.powerState()
.......and more info

Is there anyway to hit the vm directly and get the info without traversing exhaustively ?

**Comment by hartsock** [comment]
This can best be done with [searchIndex](http://pubs.vmware.com/vsphere-55/index.jsp#com.vmware.wssdk.apiref.doc/vim.SearchIndex.html). In particular you'll want to use FindChild ... but I recommend writing your code to use FindAllByDnsName, FindAllByUuid, or FindByInventoryPath.

Your code would look something like:

```

def find_vm_by_name(si, name):
    """Find a vm under the root folder or data_centers by name."""
    root_folder = si.content.rootFolder
    for data_center in root_folder.childEntity:
        search_index = si.content.searchIndex
        return search_index.FindChild(data_center, name)

```

NOTE: the return type on that method will be ManagedEntity it should resolve to VirtualMachine automatically if it doesn't we have a bug.

BTW: This would be a good class of tool to add to this project.... find_vm_by_name ... I'll make a TODO for myself.

EDIT: 

> I recommend writing your code to use FindAllByDnsName, FindAllByUuid, or FindByInventoryPath.

I recommend this behavior because managed object names are vanity identifiers and can be changed while DNS name, UUID, and inventory path are more durable.

**Comment by mygoda** [comment]
@hartsock  sorry i use this does not work，i use this to search vm. why?

**Comment by tthayer** [comment]
I ran into a problem with using the FindAllByDnsName method in that a VM that is powered off doesn't report a DNS name because the vmware tools aren't running. I used an example from https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/vminfo_quick.py to build out this function that returns a vmobject that can then be passed on to other helper functions. It takes ~10-20 seconds to return a full inventory, which isn't nearly as quick as the direct FindAllBy* methods but unless you already know the UUID you're stuck searching by name first.

```
from tools import pchelper
def get_vm_inventory(_si):
    vm_properties = ["name", "config.uuid"]
    # root_folder = _si.content.rootFolder
    view = pchelper.get_container_view(_si, obj_type=[vim.VirtualMachine])
    vm_data = pchelper.collect_properties(
        _si,
        view_ref=view,
        obj_type=vim.VirtualMachine,
        path_set=vm_properties,
        include_mors=True
    )
    return vm_data

def find_vm(_vm, _vm_data, _si):
    for item in _vm_data:
        if item['name'] == _vm:
            # print(item)
            this_uuid = item['config.uuid']
        else:
            print("VM {} could not be found in inventory.".format(_vm))
    try:
        vm = _si.content.searchIndex.FindByUuid(None, this_uuid, True)
        # print(vm)
        return vm
    except:
        print("Unable to locate VM: {}".format(_vm['name']))
```
